const express = require("express");
const cors = require("cors");
const app = express();
app.use(express.static("public"));
app.use(cors());

//github.com/jfarelli/MoodTunes-api/blob/500738ef7ebee30cc797067d0ee0e94d50b3363a/assets/happy.png

https: app.locals.data = {
  songs: [
    {
      id: 1,
      title: "Jerry Was A Race Car Driver",
      artist: "Primus",
      urlKey: "19C0LKY3DCcQtuviPJNy5d",
      genres: ["Alternative Rock", "Funk Metal", `Children's Music`],
      searchTerms: ["quirky", "fear", "weird"],
    },

    {
      id: 3,
      title: "I'll Be Missing You",
      artist: "Faith Evans and Sean Combs",
      urlKey: "3QHONiXGMGU3z68mQInncF",
      genres: ["R&B", "Soul", "Pop", "Hip-Hop", "Rap"],
      searchTerms: ["peaceful", "sad", "dreamy"],
    },
    {
      id: 4,
      title: "Grand Tour",
      artist: "George Jones",
      urlKey: "5lXX4SAV6HBaVnZ6sUQPNE",
      genres: ["Country"],
      searchTerms: ["sad"],
    },
    {
      id: 5,
      title: "Real Love Baby",
      artist: "Father John Misty",
      urlKey: "0Z57YWES04xGh3AImDz6Qr",
      genres: ["Alternative"],
      searchTerms: ["happy", "eccentric", "floating", "hopeful"],
    },
    {
      id: 6,
      title: "It Was a Good Day",
      artist: "Ice Cube",
      urlKey: "2qOm7ukLyHUXWyR4ZWLwxA",
      genres: ["Rap", "Hip-Hop"],
      searchTerms: ["epic", "floating", "laid-back", "smooth"],
    },
    {
      id: 7,
      title: "Wrongful Suspicion",
      artist: "Rancid",
      urlKey: "gsn0onH-ql8",
      genres: ["Punk-Rock", "Reggae"],
      searchTerms: ["happy", "floating", "laid-back", "smooth"],
    },
    {
      id: 8,
      title: "Cold Little Heart",
      artist: "Michael Kiwanuka",
      urlKey: "0qprlw0jfsW4H9cG0FFE0Z",
      genres: ["Soul"],
      searchTerms: ["dreamy", "elegant", "laid-back", "smooth", "sexy"],
    },
    {
      id: 9,
      title: "Psycho Killer",
      artist: "Talking Heads",
      urlKey: "7dSCxR4LqkmxoBrq9MzVSD",
      genres: ["Rock", "Alternative"],
      searchTerms: [
        "eccentric",
        "glamorous",
        "mysterious",
        "quirky",
        "weird",
        "high af",
      ],
    },
    {
      id: 10,
      title: "Brandy (You're a Fine Girl)",
      artist: "Looking Glass",
      urlKey: "2BY7ALEWdloFHgQZG6VMLA",
      genres: ["Light-Rock", "Easy-Listening"],
      searchTerms: ["happy", "floating", "laid-back"],
    },
    {
      id: 11,
      title: "My First My Last My Everything",
      artist: "Barry White",
      urlKey: "3ZYO0HGRFFdAGeb8o7F9KC",
      genres: ["Soul"],
      searchTerms: ["smooth"],
    },
    {
      id: 12,
      title: "Epic",
      artist: "Faith No More",
      urlKey: "4ReyTz0y3TGkX48wO3Llot",
      genres: ["Rock", "Alternative"],
      searchTerms: ["epic"],
    },
    {
      id: 13,
      title: "Where is My Mind",
      artist: "Maxence Cyrin",
      urlKey: "4jNQkWhuzqrbqQuqanFFJ6",
      genres: ["Piano", "Easy-Listening"],
      searchTerms: ["sad", "elegant", "relaxing", "dreamy", "floating"],
    },
    {
      id: 14,
      title: "Watching the Detectives",
      artist: "Elvis Costello - Watching the Detectives",
      urlKey: "0KrYPz4S4mKHeBjCwYJp0s",
      genres: ["Alternative", "Rock"],
      searchTerms: ["eccentric", "marching", "weird"],
    },
    {
      id: 15,
      title: "Amber",
      artist: "311",
      urlKey: "51UtgWS4z1eMPuLQOzPtNH",
      genres: ["Rock", "Reggae"],
      searchTerms: ["dreamy", "floating", "laid-back"],
    },
    {
      id: 16,
      title: "You Never Even Called Me By My Name",
      artist: "David Allan Coe",
      urlKey: "29TI0GvP5gMQMPTJjdMe0H",
      genres: ["Country"],
      searchTerms: ["funny", "quirky", "sentimental"],
    },
    {
      id: 17,
      title: "Against the Wind",
      artist: "Bob Seiger and the Silver Bullet Band",
      urlKey: "1SWmFiFSIBoDbQJjNKC7SR",
      genres: ["Rock 'n Roll"],
      searchTerms: ["laid-back", "floating", "peaceful"],
    },
    {
      id: 18,
      title: "Whispered Words",
      artist: "Dan Auerbach",
      urlKey: "6KPaX2zvWAOXYZjvhqdQZj",
      genres: ["Alternative"],
      searchTerms: ["laid-back", "floating", "peaceful"],
    },
    {
      id: 19,
      title: "Shadrach",
      artist: "Beastie Boys",
      urlKey: "2GOcde6C8b4jH17cYgKzlp",
      genres: ["Rap", "Hip-Hop"],
      searchTerms: ["eccentric", "running", "marching"],
    },
    {
      id: 20,
      title: "Take Me Home, Country Roads",
      artist: "John Denver",
      urlKey: "PnDhAhko6cDS",
      genres: ["Country", "Light-Rock"],
      searchTerms: ["eccentric", "elegant", "euphoric", "floating"],
    },
    {
      id: 21,
      title: "Push Off",
      artist: "The Palms",
      urlKey: "3869c1bl5bJqdD3cyDw8hh",
      genres: ["Alternative"],
      searchTerms: ["eccentric", "elegant", "euphoric", "floating", "smooth"],
    },
    {
      id: 22,
      title: "Walk Like an Egyption",
      artist: "The Bangles",
      urlKey: "1Jwc3ODLQxtbnS8M9TflSP",
      genres: ["Rock"],
      searchTerms: ["happy", "epic"],
    },
    {
      id: 23,
      title: "Careless Whisper",
      artist: "George Michael",
      urlKey: "4jDmJ51x1o9NZB5Nxxc7gY",
      genres: ["Light-Rock", "Glam-Rock"],
      searchTerms: [
        "eccentric",
        "epic",
        "floating",
        "laid-back",
        "sentimental",
        "high af",
      ],
    },
    {
      id: 24,
      title: "Stickin'n in My Eye",
      artist: "NOFX",
      urlKey: "46mov5j25a6BXrxNQKUwiA",
      genres: ["Punk-Rock"],
      searchTerms: ["eccentric", "epic", "running", "laid-back"],
    },
    {
      id: 25,
      title: "Desperate Times",
      artist: "Killswitch Engage",
      urlKey: "4hao5QyH9QKXi902ERMQ5D",
      genres: ["Punk-Rock"],
      searchTerms: ["angry", "dark", "fear", "scary", "heavy"],
    },
    {
      id: 26,
      title: "Beer For My Horses (ft. Willie Nelson)",
      artist: "Toby Keith",
      urlKey: "7E2DqvnVtbIrFrL5X6YH9Q",
      genres: ["Country"],
      searchTerms: ["happy", "laid-back"],
    },
    {
      id: 27,
      title: "Take Your Mama",
      artist: "Scissor Sisters",
      urlKey: "0LAfANg75hYiV1IAEP3vY6",
      genres: ["Country"],
      searchTerms: ["happy", "eccentric", "funny", "glamorous"],
    },
    {
      id: 28,
      title: "WWE Stone Cold theme song",
      artist: "The Texas Rattle Snake",
      urlKey: "7c6gwmXP64tmpbmA86wHIk",
      genres: ["Rock", "Alternative"],
      searchTerms: ["eccentric", "epic", "marching", "chasing", "fear"],
    },
    {
      id: 29,
      title: "Sexual Healing",
      artist: "Marvin Gaye",
      urlKey: "3VZmChrnVW8JK6ano4gSED",
      genres: ["R&B", "Soul"],
      searchTerms: ["romantic", "sentimental", "sexy", "smooth"],
    },

    {
      id: 30,
      title: "How Does It Feel?",
      artist: "D’Angelo",
      urlKey: "4oPNN7syJYSjzDhRerF966",
      genres: ["R&B", "Soul", "Neo Soul"],
      searchTerms: ["romantic", "sentimental", "sexy", "smooth"],
    },

    {
      id: 31,
      title: "When Doves Cry",
      artist: "Prince & The Revolution",
      urlKey: "UG3VcCAlUgE",
      genres: ["R&B", "Soul"],
      searchTerms: ["sad", "sentimental"],
    },

    {
      id: 32,
      title: `Let's Go Crazy`,
      artist: "Prince & The Revolution",
      urlKey: "51H2y6YrNNXcy3dfc3qSbA",
      genres: ["R&B", "Soul"],
      searchTerms: [
        "glamorous",
        "happy",
        "hopeful",
        "eccentric",
        "euphoric",
        "quirky",
      ],
    },

    {
      id: 33,
      title: ` Purple Rain`,
      artist: "Prince",
      urlKey: "54X78diSLoUDI3joC2bjMz",
      genres: ["R&B", "Soul"],
      searchTerms: ["glamorous", "sad", "sentimental"],
    },

    {
      id: 34,
      title: "In The Air Tonight",
      artist: "Phil Collins",
      urlKey: "YkADj0TPrJA",
      genres: ["Alternative", "Indie", "R&B", "Soul", "Pop", "Rock"],
      searchTerms: ["peaceful", "dreamy", "floating", "high af"],
    },
    {
      id: 35,
      title: "Africa",
      artist: "Toto",
      urlKey: "18AXbzPzBS8Y3AkgSxzJPb",
      genres: ["Pop"],
      searchTerms: ["happy", "epic"],
    },
    {
      id: 36,
      title: "Gooey",
      artist: "Glass Animals",
      urlKey: "jeo3an2M_Lo",
      genres: ["Alternative", "Indie", "R&B", "Soul", "Pop"],
      searchTerms: ["happy", "euphoric", "floating", "high af"],
    },

    {
      id: 37,
      title: "C.R.E.A.M.",
      artist: "Wu-Tang Clan",
      urlKey: "PBwAxmrE194",
      genres: ["Rap", "Hip-hop"],
      searchTerms: ["hopeful", "high af"],
    },

    {
      id: 38,
      title: "Kerala",
      artist: "Bonobo",
      urlKey: "S0Q4gqBUs7c",
      genres: ["Alternative", "Indie", "Dance", "Electronic"],
      searchTerms: [
        "relaxing",
        "dreamy",
        "floating",
        "hopeful",
        "euphoric",
        "high af",
      ],
    },

    {
      id: 39,
      title: "You & Me (Flume Remix)",
      artist: "MEUTE",
      urlKey: "fKFbnhcNnjE",
      genres: ["Techno", "Deep House", "House"],
      searchTerms: ["marching", "happy", "epic"],
    },

    {
      id: 40,
      title: "Mile High",
      artist: "James Blake",
      urlKey: "PWPafG8wEvc",
      genres: ["Dance", "Electronic"],
      searchTerms: [
        "sentimental",
        "dreamy",
        "smooth",
        "peaceful",
        "mysterious",
      ],
    },
    {
      id: 41,
      title: "Hero",
      artist: "Enrique Iglesias",
      urlKey: "koJlIGDImiU",
      genres: ["Light-Rock", "Easy-Listening"],
      searchTerms: ["sexy", "romantic"],
    },
    {
      id: 42,
      title: "I Want it That Way",
      artist: "Backstreet Boys",
      urlKey: "4fndeDfaWCg",
      genres: ["Alternative", "Boy-Band"],
      searchTerms: ["sexy", "romantic", "high af"],
    },
    {
      id: 43,
      title: "End of the Road",
      artist: "Boyz II Men",
      urlKey: "zDKO6XYXioc",
      genres: ["R&B", "Soul"],
      searchTerms: ["sexy", "romantic"],
    },
    {
      id: 44,
      title: "How Am I Supposed To Live Without You",
      artist: "Michael Bolton",
      urlKey: "YFood_bTOX4",
      genres: ["Soul"],
      searchTerms: ["sexy", "romantic", "studious"],
    },
    {
      id: 45,
      title: "Nobody Speak (ft. Run The Jewels)",
      artist: "DJ Shadow",
      urlKey: "NUC2EQvdzmY",
      genres: ["Rap", "Hip-Hop"],
      searchTerms: ["epic", "running"],
    },
    {
      id: 46,
      title: "Die By the Drop",
      artist: "The Dead Weather",
      urlKey: "K0YI0UUazkU",
      genres: ["Rock"],
      searchTerms: ["epic", "running", "heavy"],
    },
    {
      id: 47,
      title: "Steal Away",
      artist: "Murder by Death",
      urlKey: "e4o875fwWtA",
      genres: ["Alternative"],
      searchTerms: ["dark", "essentric", "mysterious"],
    },
    {
      id: 48,
      title: "Time After Time",
      artist: "Cindy Lauper",
      urlKey: "VdQY7BusJNU",
      genres: ["Alternative"],
      searchTerms: ["romantic", "elegant", "sentimental"],
    },
    {
      id: 49,
      title: "Van Helsing Boombox",
      artist: "Man Man",
      urlKey: "rOaee8Qss0w",
      genres: ["Alternative"],
      searchTerms: ["essentric", "quirky", "weird"],
    },
    {
      id: 50,
      title: "With a Little Help from My Friends",
      artist: "Joe Cocker",
      urlKey: "nCrlyX6XbTU",
      genres: ["Rock"],
      searchTerms: ["essentric", "epic"],
    },
    {
      id: 51,
      title: "Fuck You Bitch",
      artist: "Wheeler Walker Jr.",
      urlKey: "myJDBos5Vyw",
      genres: ["Country"],
      searchTerms: ["essentric", "funny", "quirky", "weird"],
    },
    {
      id: 52,
      title: "Rocket Man (I Think It's Going to Be a Long, Long Time)",
      artist: "Elton John",
      urlKey: "DtVBCG6ThDk",
      genres: ["Rock"],
      searchTerms: ["epic", "floating"],
    },
    {
      id: 53,
      title: "It's Too Late",
      artist: "Rodney Carrington",
      urlKey: "P7rTUTedclw",
      genres: ["Country"],
      searchTerms: ["funny", "quirky"],
    },
    {
      id: 54,
      title: "Easy",
      artist: "Faith No More",
      urlKey: "vPzDTfIb0DU",
      genres: ["Alternative", "Rock"],
      searchTerms: ["laid-back", "relaxing"],
    },
    {
      id: 55,
      title: "Thunder Kiss '65",
      artist: "White Zombie",
      urlKey: "yPNFVj-pISU",
      genres: ["Metal", "Hard-Rock"],
      searchTerms: ["heavy", "dark", "angry"],
    },
    {
      id: 56,
      title: "No Rain",
      artist: "Blind Melon",
      urlKey: "3qVPNONdF58",
      genres: ["Alternative"],
      searchTerms: ["laid-back", "happy", "quirky"],
    },
    {
      id: 57,
      title: "They Love Each Other",
      artist: "Grateful Dead",
      urlKey: "58JTV8kW2_8",
      genres: ["Rock", "Alternative"],
      searchTerms: [
        "sexy",
        "sentimental",
        "euphoric",
        "romantic",
        "peaceful",
        "smooth",
        "dreamy",
        "high af",
      ],
    },

    {
      id: 58,
      title: "You Sexy Thing",
      artist: "Hot Chocolate",
      urlKey: "YUY9Y9RFiHY",
      genres: ["R&B", "Soul"],
      searchTerms: ["eccentric", "glamorous", "mysterious", "quirky", "weird"],
    },

    {
      id: 59,
      title: "Lovely Day",
      artist: "Bill Withers",
      urlKey: "bEeaS6fuUoA",
      genres: ["R&B", "Soul"],
      searchTerms: [
        "sentimental",
        "euphoric",
        "romantic",
        "peaceful",
        "smooth",
        "dreamy",
        "high af",
      ],
    },

    {
      id: 60,
      title: "Do Right Woman, Do Right Man",
      artist: "Aretha Franklin",
      urlKey: "VhdgFfNsst0",
      genres: ["R&B", "Soul"],
      searchTerms: [
        "relaxing",
        "happy",
        "glamourous",
        "sexy",
        "sentimental",
        "euphoric",
        "romantic",
        "peaceful",
        "smooth",
        "dreamy",
      ],
    },

    {
      id: 61,
      title: "Silent in the Morning",
      artist: "Phish",
      urlKey: "Sbh8b45WN5A",
      genres: ["Rock"],
      searchTerms: [
        "sentimental",
        "euphoric",
        "peaceful",
        "smooth",
        "dreamy",
        "happy",
        "relaxing",
        "elegant",
        "epic",
        "high af",
      ],
    },
    {
      id: 63,
      title: "Bassackwards",
      artist: "Kurt Vile",
      urlKey: "pOFWHty4XFQ",
      genres: ["Alternative", "Indie"],
      searchTerms: [
        "sentimental",
        "peaceful",
        "smooth",
        "dreamy",
        "happy",
        "relaxing",
        "elegant",
        "epic",
      ],
    },
    {
      id: 64,
      title: "Dear Prudence",
      artist: "Jerry Garcia",
      urlKey: "qKHh1eCwwno",
      genres: ["Rock", "Jam", "Psychedelia"],
      searchTerms: [
        "sentimental",
        "euphoric",
        "peaceful",
        "smooth",
        "dreamy",
        "happy",
        "relaxing",
        "elegant",
        "epic",
        "high af",
      ],
    },
    {
      id: 66,
      title: "Darker Thoughts",
      artist: "Paradise Lost",
      urlKey: "URJH3ZJzxB0",
      genres: ["Metal"],
      searchTerms: ["dark", "sad", "heavy"],
    },
    {
      id: 67,
      title: "My Twin",
      artist: "Katatonia",
      urlKey: "nH45PdkXF9I",
      genres: ["Metal", "Rock"],
      searchTerms: ["dark", "sad"],
    },
    {
      id: 68,
      title: "Carnival of Rust",
      artist: "Poets of the Fall",
      urlKey: "MKk1u5RMTn4",
      genres: ["Rock"],
      searchTerms: ["sad", "mysterious"],
    },
    {
      id: 69,
      title: "Make it Bun Dem",
      artist: "Skrillex & Damien",
      urlKey: "BGpzGu9Yp6Y",
      genres: ["Dubstep", "Reggae"],
      searchTerms: ["high af", "eccentric"],
    },
    {
      id: 70,
      title: "Minds Playin Tricks On Me",
      artist: "Geto Boys",
      urlKey: "IJtHdkyo0hc",
      genres: ["Rap", "Gangsta Rap"],
      searchTerms: ["high af", "dark", "restless", "mysterious"],
    },
    {
      id: 71,
      title: "ILL MIND OF HOPSIN 5",
      artist: "Hopsin",
      urlKey: "hRVOOwFNp5U",
      genres: ["Rap"],
      searchTerms: ["dark", "scary"],
    },

    {
      id: 72,
      title: "Set Trippin",
      artist: "Casanova",
      urlKey: "YiS24Ia44DQ",
      genres: ["Rap", "Gangsta Rap"],
      searchTerms: ["dark", "high af", "eccentric"],
    },
    {
      id: 73,
      title: "Can't Be Touched",
      artist: "Roy Jones Jr",
      urlKey: "ivPKDBzVhow",
      genres: ["Rap", "Gangsta Rap"],
      searchTerms: ["dark", "high af", "eccentric", "epic"],
    },
    {
      id: 74,
      title: "Panzerkampf",
      artist: "Sabaton",
      urlKey: "3vEW_r4Swn8",
      genres: ["Metal", "Heavy Metal", ""],

      searchTerms: ["marching", "eccentric", "epic"],
    },
    {
      id: 75,
      title: "Disillusion in a Discordant System",
      artist: "Acrania",
      urlKey: "ArrqUWKvq7g",
      genres: ["Metal", "Death Metal", "Speed Metal"],

      searchTerms: ["eccentric", "epic", "scary"],
    },
    {
      id: 76,
      title: "The Bleeding",
      artist: "Five Finger Death Punch",
      urlKey: "KAuyEG7JPbE",
      genres: ["Metal", "Heavy Metal", "Nu Metal"],
      searchTerms: ["dark", "scary", "sad", "heay"],
    },
    {
      id: 76,
      title: "Runnin Up That Hill",
      artist: "Kate Bush",
      urlKey: "wp43OdtAAkM",
      genres: ["Alternative", "Pop"],
      searchTerms: ["floating", "eccentric", "euphoric"],
    },
    {
      id: 77,
      title: "Total Eclipse of The Heart",
      artist: "Bonnie Tyler",
      urlKey: "lcOxhH8N3Bo",
      genres: ["Alternative", "Pop"],
      searchTerms: ["epic", "eccentric", "euphoric", "dreamy"],
    },
    {
      id: 78,
      title: "I Was Made For Lovin' You",
      artist: "Kiss",
      urlKey: "12fJAnaif34",
      genres: ["Rock", "Classic Rock"],
      searchTerms: ["epic", "euphoric", "hopeful"],
    },
    {
      id: 79,
      title: "Like a Stone",
      artist: "Audioslave",
      urlKey: "7QU1nvuxaMA",
      genres: ["Rock", "Classic Rock"],
      searchTerms: ["dark", "Sad"],
    },
    {
      id: 80,
      title: "Black Hole Sun",
      artist: "Soundgarden",
      urlKey: "3mbBbFH9fAg",
      genres: ["Rock"],
      searchTerms: ["dark", "sad", "sentimental"],
    },
    {
      id: 81,
      title: "(Don't Fear) The Reaper",
      artist: "Blue Oyster Cult",
      urlKey: "Dy4HA3vUv2c",
      genres: [
        "Hard rock",
        "Psychedelic",
        "rock",
        "Soft rock",
        "Alternative",
        "Indie",
        `Children's Music`,
        "Pop",
        "Rock",
      ],
      searchTerms: ["fear", "dark"],
    },
    {
      id: 82,
      title: "Iron Man",
      artist: "Black Sabbath",
      urlKey: "F01UTYg79KY",
      genres: ["Metal", "Rock"],
      searchTerms: ["fear", "dark"],
    },
    {
      id: 83,
      title: "Running Up That Hill",
      artist: "Kate Bush",
      urlKey: "wp43OdtAAkM",
      genres: ["New wave", "Alternative", "Indie", "Pop", "Holiday", "Folk"],
      searchTerms: ["fear", "chasing"],
    },
    {
      id: 84,
      title: "Riders On The Storm",
      artist: "The Doors",
      urlKey: "iv8GW1GaoIc",
      genres: [
        "Psychedelic rock",
        "Jazz fusion",
        "Gothic rock",
        "Alternative",
        "Indie",
        "Art rock",
        `Children's Music`,
        "Rock",
        "Blues",
        "Folk",
      ],
      searchTerms: ["fear", "chasing"],
    },

    {
      id: 85,
      title: "Pelota",
      artist: "Khruangbin",
      urlKey: "UULIfPLMuDw",
      genres: ["Alternative", "Indie"],
      searchTerms: ["laid back", "sexy"],
    },

    {
      id: 86,
      title: `I'm Solo`,
      artist: "Claude VonStroke",
      urlKey: "5HIZaxq5EfM",
      genres: ["Jungle", "Drum", "Bass", "House"],
      searchTerms: ["restless", "high af", "floating"],
    },
    {
      id: 87,
      title: `Crazy Train`,
      artist: "Ozzy Osbourne",
      urlKey: "tMDFv5m18Pw",
      genres: ["Heavy Metal", "Metal"],
      searchTerms: ["chasing", "dark"],
    },
    {
      id: 88,
      title: `I Thought About Killing You`,
      artist: "Kanye West",
      urlKey: "no1YszVVybo",
      genres: ["Hip Hop ", "Rap"],
      searchTerms: ["dark"],
    },
    {
      id: 89,
      title: `Still Fly`,
      artist: "Big Tymers",
      urlKey: "9iCd6UHR-3I",
      genres: ["Hip Hop ", "Rap"],
      searchTerms: ["funny", "high af"],
    },
    {
      id: 90,
      title: `New York, New York`,
      artist: "Frank Sinatra",
      urlKey: "EEjq8ZoyXuQ",
      genres: ["Jazz"],
      searchTerms: ["elegant"],
    },
    {
      id: 91,
      title: `Blow Horn Joint`,
      artist: "DJ Premier",
      urlKey: "VgYzsbVvk5s",
      genres: ["Hip Hop", "Rap", "Jazz"],
      searchTerms: ["elegant"],
    },
    {
      id: 92,
      title: `Suicidal Thoughts`,
      artist: "The Notorious B.I.G.",
      urlKey: "v1mKGlYL9jg",
      genres: ["Hip Hop", "Rap"],
      searchTerms: ["dark"],
    },
    {
      id: 93,
      title: `Rudolph The Red Nosed Reindeer`,
      artist: "DMX",
      urlKey: "B4W_XYI4AN0",
      genres: ["Hip Hop", "Rap"],
      searchTerms: ["funny", "high af"],
    },
    {
      id: 94,
      title: `Just the Two of Us`,
      artist: "Grover Washington Jr.",
      urlKey: "6POZlJAZsok",
      genres: ["Jazz", "Soul music", "Rhythm and blues"],
      searchTerms: ["sexy", "smooth"],
    },
    {
      id: 95,
      title: `Halloween Theme Song`,
      artist: "Michael Myers",
      urlKey: "2T9m-fj8K9c",
      genres: ["Classical"],
      searchTerms: ["fear", "chasing", "dark"],
    },
    {
      id: 96,
      title: `Nocturne op.9 No.2`,
      artist: "Chopin",
      urlKey: "9E6b3swbnWg",
      genres: ["Piano"],
      searchTerms: ["elegant", "sad"],
    },
    {
      id: 97,
      title: `Cello Suite No. 1 in G Major BWV1007`,
      artist: "Bach",
      urlKey: "DwHpDOWhkGk",
      genres: ["Piano"],
      searchTerms: ["elegant"],
    },
    {
      id: 98,
      title: `Werewolf Bar Mitzvah`,
      artist: "Tracy Morgan",
      urlKey: "A6V2oCX3Hn4",
      genres: ["Funny"],
      searchTerms: ["funny"],
    },
    {
      id: 99,
      title: `Con Te Partirò`,
      artist: "Andrea Bocelli",
      urlKey: "TdWEhMOrRpQ",
      genres: ["Operatic pop"],
      searchTerms: ["elegant"],
    },
    {
      id: 100,
      title: "I'll Be Here in the Morning",
      artist: "Townes Van Zandt",
      urlKey: "SCVTjmygWuU",
      genres: ["Alternative", "Country", "Rock"],
      searchTerms: ["peaceful", "dreamy", "sentimental", "romantic"],
    },
    {
      id: 101,
      title: "Fearless",
      artist: "Pink Floyd",
      urlKey: "sl_apx8JoMwYkADj0TPrJA",
      genres: ["Rock"],
      searchTerms: ["happy", "epic", "dreamy", "relaxing"],
    },
    {
      id: 102,
      title: "The Morning Light",
      artist: "Billy Strings",
      urlKey: "kx3NOJ-oCfo",
      genres: ["country"],
      searchTerms: [
        "happy",
        "euphoric",
        "floating",
        "high af",
        "romantic",
        "sexy",
        "peaceful",
        "sentimental",
      ],
    },

    {
      id: 103,
      title: "Miracles",
      artist: "ICP",
      urlKey: "8GyVx28R9-s",
      genres: ["Rap", "Hip-hop"],
      searchTerms: ["weird"],
    },

    {
      id: 104,
      title: "Most Events Aren't Planned",
      artist: "Phish",
      urlKey: "8r1iVVEn2Hc",
      genres: ["Rock"],
      searchTerms: ["epic", "euphoric", "high af", "dark", "mysterious"],
    },

    {
      id: 105,
      title: "Awake",
      artist: "Tycho",
      urlKey: "6XJBDX3Z0BY",
      genres: ["Dance"],
      searchTerms: ["studious", "sentimental", "smooth"],
    },

    {
      id: 106,
      title: "Dragula",
      artist: "Rob Zombie",
      urlKey: "EqQuihD0hoI",
      genres: ["Dance", "Electronic"],
      searchTerms: ["weird", "scary"],
    },
    {
      id: 107,
      title: "Carini",
      artist: "Phish",
      urlKey: "rGIg9w9qmlA",
      genres: ["Rock"],
      searchTerms: ["scary", "weird"],
    },
    {
      id: 108,
      title: " Poison",
      artist: "Alice Cooper",
      urlKey: "Qq4j1LtCdww",
      genres: ["Glamrock", "Rock"],
      searchTerms: ["glamorous", "romantic"],
    },
    {
      id: 109,
      title: "18 & life",
      artist: "Skid Row",
      urlKey: "Ghd2bkIadG4",
      genres: ["Glamrock", "Rock"],
      searchTerms: ["glamorous", "dark", "sad"],
    },
    {
      id: 110,
      title: "Cherry Pie",
      artist: "Warrant",
      urlKey: "OjyZKfdwlng",
      genres: ["Glamrock", "Rock"],
      searchTerms: ["glamorous", "eccentric", "euphoric"],
    },
    {
      id: 111,
      title: " Kickstart My Heart",
      artist: "Mötley Crüe",
      urlKey: "WqOlHt--fOI",
      genres: ["Glamrock", "Metal"],
      searchTerms: ["glamorous", "eccentric"],
    },
    {
      id: 112,
      title: "Dream On",
      artist: "Aerosmith",
      urlKey: "cvCFRGn7EEQ",
      genres: ["Glamrock", "Rock"],
      searchTerms: ["glamorous", "eccentric", "epic"],
    },
    {
      id: 113,
      title: "Flying Whales",
      artist: "Gojira",
      urlKey: "_-XaaTqOICU",
      genres: ["Metal", "Heavy Metal"],
      searchTerms: ["heavy", "epic"],
    },
    {
      id: 114,
      title: "Wherein Lies Continue",
      artist: "Slipknot",
      urlKey: "LWRzceFXYPc",
      genres: ["Metal", "Heavy Metal"],
      searchTerms: ["heavy", "epic", "dark"],
    },
    {
      id: 115,
      title: "To Hell and Back",
      artist: "Sabaton",
      urlKey: "LWRzceFXYPc",
      genres: ["Metal", "Heavy Metal"],
      searchTerms: ["heavy", "marching"],
    },
    {
      id: 116,
      title: "In the Name of God",
      artist: "Powerwolf",
      urlKey: "GCN1s9g9Mfo",
      genres: ["Metal", "Heavy Metal"],
      searchTerms: ["eccentric", "marching"],
    },
    {
      id: 117,
      title: "Carolus Rex ",
      artist: "Sabaton",
      urlKey: "K75H32uBeAU",
      genres: ["Metal", "Heavy Metal"],
      searchTerms: ["eccentric", "marching"],
    },
    {
      id: 119,
      title: "Wind of Change",
      artist: "Scorpions",
      urlKey: "K75H32uBeAU",
      genres: ["Rock"],
      searchTerms: ["epic", "marching", "sentimental", "hopeful"],
    },
    {
      id: 120,
      title: "They Don't Really Care About Us",
      artist: "Michael Jackson",
      urlKey: "t1pqi8vjTLY",
      genres: ["Pop"],
      searchTerms: ["hopeful", "sentimental"],
    },
    {
      id: 121,
      title: "Holding Out For a Hero",
      artist: "Bonnie Tyler",
      urlKey: "bWcASV2sey0",
      genres: ["Pop"],
      searchTerms: ["hopeful", "sentimental", "epic"],
    },
    {
      id: 122,
      title: "I'd Do Anything For Love",
      artist: "Meatloaf",
      urlKey: "9X_ViIPA-Gc",
      genres: ["Rock", "Alternative"],
      searchTerms: ["hopeful", "sentimental", "epic", "romantic"],
    },
    {
      id: 123,
      title: "Waiting Room",
      artist: "Fugazi",
      urlKey: "C3LXkdpHNOQ",
      genres: ["Punk-Rock"],
      searchTerms: ["Restless"],
    },
    {
      id: 124,
      title: "X",
      artist: "Xzibit",
      urlKey: "qJxk1leG1wY",
      genres: ["Rap"],
      searchTerms: ["Restless"],
    },
    {
      id: 125,
      title: "Jump Around",
      artist: "House of Pain",
      urlKey: "jrL_LzX5wv4",
      genres: ["Rap", "Hip-Hop"],
      searchTerms: ["Restless", "Running"],
    },
    {
      id: 126,
      title: "Summertime",
      artist: "DJ Jazzy Jeff & The Fresh Prince",
      urlKey: "Kr0tTbTbmVA",
      genres: ["Rap", "Hip-Hop"],
      searchTerms: ["Quirky"],
    },
    {
      id: 127,
      title: "Mysterious Ways",
      artist: "U2",
      urlKey: "TxcDTUMLQJI",
      genres: ["Rock", "Alternative"],
      searchTerms: ["mysterious"],
    },
    {
      id: 128,
      title: "4 AM",
      artist: "Kaskade",
      urlKey: "kV0IBNHWFeg",
      genres: ["Alternative"],
      searchTerms: ["mysterious"],
    },
    {
      id: 129,
      title: "Spring Break 1899",
      artist: "Murder By Death",
      urlKey: "ftYle2UOjYk",
      genres: ["Alternative"],
      searchTerms: ["mysterious"],
    },
    {
      id: 130,
      title: "Closer",
      artist: "Kings of Leon",
      urlKey: "Qf92fQDITgc",
      genres: ["Alternative"],
      searchTerms: ["mysterious"],
    },
    {
      id: 131,
      title: "Ashamed",
      artist: "Deer Tick",
      urlKey: "TILo-c-mpGE",
      genres: ["Alternative"],
      searchTerms: ["mysterious"],
    },
    {
      id: 132,
      title: "Waiting Room",
      artist: "Fugazi",
      urlKey: "C3LXkdpHNOQ",
      genres: ["Punk-Rock"],
      searchTerms: ["restless"],
    },
  ],

  moods: [
    {
      id: 1,
      title: "Happy",
      img: `https://www.2ndacthealth.com/wp-content/uploads/2015/10/wallpaper-beach-happy-people.jpg`,
    },
    {
      id: 2,
      title: "Relaxing",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSrCGfXMJiywhO1wChl5TR5MCZJFkVPF--XEQ&usqp=CAU",
    },
    {
      id: 3,
      title: "Dreamy",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS8qTPQt7hnD5Y1vF9uOpvReiy-4s7JDjEVaQ&usqp=CAU",
    },
    {
      id: 4,
      title: "Glamorous",
      img: "https://i.pinimg.com/originals/84/41/83/844183a3111f09d04abbdd974a0305c6.jpg",
    },
    {
      id: 5,
      title: "Elegant",
      img: "https://memegenerator.net/img/images/73326557.jpg",
    },
    {
      id: 6,
      title: "Epic",
      img: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2016/12/15/11/stone-cold-beer.jpg?quality=75&width=982&height=726&auto=webp",
    },
    {
      id: 7,
      title: "Sad",
      img: "https://media.istockphoto.com/photos/depressed-woman-sitting-on-a-chair-in-dark-room-at-home-lonly-sad-picture-id865618914?b=1&k=20&m=865618914&s=170667a&w=0&h=D0AppFdYGgOlQZ4rcs90tWYf0ZDAxfUgZ9oA5fPmxQ8=",
    },
    {
      id: 8,
      title: "Smooth",
      img: "https://i.scdn.co/image/d04ae222146d052fbbe9ed2598c1c3319d4e7ebc",
    },
    {
      id: 9,
      title: "High AF",
      img: "https://w0.peakpx.com/wallpaper/424/116/HD-wallpaper-take-me-away-aesthetic-ballons-clouds-dreamy-floating-mood-soft-takemeaway.jpg",
    },
    {
      id: 10,
      title: "Sexy",
      img: "https://img.buzzfeed.com/buzzfeed-static/static/2019-01/8/14/tmp/buzzfeed-prod-web-05/tmp-name-2-23747-1546977174-0_dblbig.jpg?output-format=auto&output-quality=auto&resize=300:*;",
    },
    {
      id: 11,
      title: "Eccentric",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 12,
      title: "Chasing",
      img: "https://www.business2community.com/wp-content/uploads/2018/02/BeingChased-600x400.jpg",
    },
    {
      id: 13,
      title: "Hopeful",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 14,
      title: "Marching",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 15,
      title: "Mysterious",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 16,
      title: "Peaceful",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 17,
      title: "Quirky",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 18,
      title: "Dark",
      img: "https://i.scdn.co/image/ab67706c0000bebb59945d1c8e4430b6ad5f2207",
    },
    {
      id: 19,
      title: "Restless",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 20,
      title: "Romantic",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 21,
      title: "Running",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 22,
      title: "Euphoric",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 23,
      title: "Scary",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 24,
      title: "Sentimental",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 25,
      title: "Funny",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 26,
      title: "Fear",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
    {
      id: 27,
      title: "Floating",
      img: "https://w0.peakpx.com/wallpaper/424/116/HD-wallpaper-take-me-away-aesthetic-ballons-clouds-dreamy-floating-mood-soft-takemeaway.jpg",
    },
    {
      id: 28,
      title: "Weird",
      img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRomK6c1C-ls2QaArwg5b6FCzmR0k93r13cwg&usqp=CAU",
    },
  ],
};

app.get("/:id", (request, response) => {
  const data = app.locals.songs;
  let foundSong = data.find((song) => song.id === parseInt(request.params.id));
  if (!foundSong) {
    response.status(404).send({
      error: `Sorry this song doesn't exist yet!`,
    });
  }
  response.send({ foundSong });
});

app.set("port", process.env.PORT || 3001);
app.locals.title = "MoodTunes-api";

app.get("/", (request, response) => {
  const data = app.locals.data;
  if (!data) {
    response.status(404).send({
      error: `Sorry this server is down!`,
    });
  }
  response.send({ data });
});

app.listen(app.get("port"), () => {
  console.log(
    `${app.locals.title} is running on http://localhost:${app.get("port")}.`
  );
});
